"""Add User and Settings models

Revision ID: ba70e5123d76
Revises: 
Create Date: 2025-04-19 19:58:00.176638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba70e5123d76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_value', sa.Float(), nullable=False))
        batch_op.drop_column('value')
        batch_op.drop_column('flex')
        batch_op.drop_column('emg')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emg', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('flex', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=False))
        batch_op.drop_column('data_value')

    # ### end Alembic commands ###
